// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvvX5c92_UrdtgyLaaHbcKwrfeFX4uXWY',
    appId: '1:366618222896:web:a0f0507cc95c5a968f28f5',
    messagingSenderId: '366618222896',
    projectId: 'tooo-10028',
    authDomain: 'tooo-10028.firebaseapp.com',
    storageBucket: 'tooo-10028.appspot.com',
    measurementId: 'G-PWF6K5RMLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxQN_4IkR3jXO0nQb1XDecfJz0ZUQOtw',
    appId: '1:366618222896:android:edd28826cdf180688f28f5',
    messagingSenderId: '366618222896',
    projectId: 'tooo-10028',
    storageBucket: 'tooo-10028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBcjj2k3rhrtCalke6NSHt9Qo-NfioMR0',
    appId: '1:366618222896:ios:b0607eefb49be95d8f28f5',
    messagingSenderId: '366618222896',
    projectId: 'tooo-10028',
    storageBucket: 'tooo-10028.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBcjj2k3rhrtCalke6NSHt9Qo-NfioMR0',
    appId: '1:366618222896:ios:599d14907c8e68628f28f5',
    messagingSenderId: '366618222896',
    projectId: 'tooo-10028',
    storageBucket: 'tooo-10028.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
